[workspace]
resolver = "3"
exclude = ["target/", "Cargo.lock", ".github/"]

members = [
    # main crates
    "crates/*",
    # examples
    "examples/*",
]
default-members = ["crates/furl"]

[workspace.package]
license = "Apache-2.0"
version = "0.8.1"
edition = "2024"



[workspace.dependencies]
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros"] }
