[package]
name = "furl-core"
description = "A fast, multithreaded downloader library built in Rust."
version = "0.9.1"
edition.workspace = true
license.workspace = true
publish = true
readme = "README.md"
authors = ["Sudip Ghimire"]
homepage = "https://github.com/ghimiresdp/furl-cli"
repository = "https://github.com/ghimiresdp/furl-cli"
keywords = [
  "downloader",
  "multithreaded",
  "download-library",
  "network-programming",
]
categories = ["network-programming", "asynchronous"]
exclude = ["target/", "Cargo.lock", ".github/", "examples/"]

[lib]
name = "furl_core"
path = "src/lib.rs"

[features]
progress = ["dep:indicatif"]

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
futures-util = "0.3.32"
regex = "1.12.3"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
clap = { version = "4.6.1", features = ["derive"], optional = true }
indicatif = { version = "0.18.4", optional = true }


[package.metadata.workspaces]
independent = true
